ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.flightpricealert.ApplicationKt.module ]
  }
}

flight-price-alert {
  amadeus {
    clientId = ""
    clientSecret = ""
  }
  smtp {
    host = ""
    port = 587
    user = ""
    password = ""
  }
  scheduler {
    intervalHours = 6
  }
  database {
    url = "jdbc:h2:mem:flightdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    user = "sa"
    password = ""
  }
}


