package com.flightpricealert.repository

import com.flightpricealert.config.AppConfig
import java.sql.Connection
import java.sql.DriverManager

object DatabaseFactory {
    @Volatile
    private var initialized = false

    @Volatile
    var activeDbUrl: String = ""
        private set

    @Volatile
    var activeDbUser: String = ""
        private set

    @Volatile
    var activeDbPassword: String = ""
        private set

    fun init(config: AppConfig) {
        synchronized(this) {
            if (initialized) return

            activeDbUrl = config.dbUrl
            activeDbUser = config.dbUser
            activeDbPassword = config.dbPassword

            createSchema()
            initialized = true
        }
    }

    fun <T> useConnection(block: (Connection) -> T): T {
        check(initialized) { "DatabaseFactory was not initialized" }
        DriverManager.getConnection(activeDbUrl, activeDbUser, activeDbPassword).use { connection ->
            return block(connection)
        }
    }

    fun reset() {
        useConnection { connection ->
            connection.createStatement().use { statement ->
                statement.executeUpdate("DELETE FROM notification_logs")
                statement.executeUpdate("DELETE FROM price_history")
                statement.executeUpdate("DELETE FROM flight_alerts")
            }
        }
    }

    fun ping(): Boolean = try {
        useConnection { connection -> connection.isValid(2) }
    } catch (_: Throwable) {
        false
    }

    private fun createSchema() {
        DriverManager.getConnection(activeDbUrl, activeDbUser, activeDbPassword).use { connection ->
            connection.createStatement().use { statement ->
                statement.executeUpdate(
                    """
                    CREATE TABLE IF NOT EXISTS flight_alerts (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        origin VARCHAR(10) NOT NULL,
                        destination VARCHAR(10) NOT NULL,
                        departure_date_from DATE NOT NULL,
                        departure_date_to DATE NULL,
                        target_price DOUBLE PRECISION NULL,
                        airlines VARCHAR(1000) NULL,
                        active BOOLEAN NOT NULL,
                        created_at TIMESTAMP NULL
                    )
                    """.trimIndent()
                )
                statement.executeUpdate(
                    """
                    CREATE TABLE IF NOT EXISTS price_history (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        alert_id INTEGER NOT NULL,
                        price DOUBLE PRECISION NOT NULL,
                        checked_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_price_history_alert FOREIGN KEY (alert_id) REFERENCES flight_alerts(id) ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
                statement.executeUpdate(
                    """
                    CREATE TABLE IF NOT EXISTS notification_logs (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        alert_id INTEGER NOT NULL,
                        price DOUBLE PRECISION NOT NULL,
                        sent_at TIMESTAMP NOT NULL,
                        recipient VARCHAR(255) NULL,
                        CONSTRAINT fk_notification_logs_alert FOREIGN KEY (alert_id) REFERENCES flight_alerts(id) ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
            }
        }
    }
}



